server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:

  datasource:
     url: jdbc:mysql://localhost:3306/login
     username: root
     password: 1234
     driver-class-name: com.mysql.cj.jdbc.Driver



logging:
  level:
    com.example: debug

